#!/bin/bash
wikidir="/usr/share/doc/arch-wiki/html/en/"
wikidocs="$(find /usr/share/doc/arch-wiki/html/en/ -iname *.html)"

main() { 
	choice=$(printf '%s\n' "${wikidocs[@]}" | cut -d '/' -f8- | sed -e 's/_/ /g' -e 's/.html//g'| sort | dmenu -i -l 20 -p "Arch Docs: ") || exit 1
	if [ "$choice" ]; then
	article=$(printf '%s\n' "${wikidir}${choice}.html" | sed 's/ /_/g')
	firefox "$article"
	else
	echo "program terminated"
	fi
}
main

