#!/bin/bash
cd /
dotpath="$(find /home/someone/.config/ -iname *.*)"
choice=$(printf '%s\n' "${dotpath[@]}" | sort | dmenu -i -l 20 -p "Edit Config: ") || exit 1
if [ "$choice" ]; then
	alacritty -e nvim "$choice"
else
	echo "program terminated"
fi
